#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

project 'LearningSwift.xcodeproj'

target 'LearningSwift' do
    use_frameworks!
    pod 'Alamofire'
    pod 'HandyJSON', '~> 5.0.2'
    pod 'Kingfisher', '~>7.0'
    pod 'SnapKit', '~> 5.6.0'
end
